### ISSUE TITLE
Stopping jobs doesn't work/causes zombies

### ISSUE THREAD

**Issue by grembo** [trivago/nomad-pot-driver#16]
Hi,

Stopping pots doesn't work properly, it never finishes, the pot stays around and there is a zombie child process to the driver.

If the command is prefixed with _exec_, making the process take tinirc's pid, it works as expected, example job description:
```
        command = "exec"
        args = [ 
          "nginx -g 'daemon off;'"
        ]
```
This can/should probably fixed in pizzamig/pot, I'll check and might open a pull request there.

**Comment by ebarriosjr** [comment]
Hi. Thanks for opening this issue. Wich version of pot are you running? Can you paste the nomad.log of when you try to stop the pot? FYI @pizzamig

**Comment by grembo** [comment]
> Hi. Thanks for opening this issue. Wich version of pot are you running? Can you paste the nomad.log of when you try to stop the pot? FYI @pizzamig

Latest version from the ports tree. I can check for logs after dinner, maybe you can take a look at the proposed patch in the meantime: https://github.com/pizzamig/pot/pull/81

**Comment by pizzamig** [comment]
We usually have only one process running in one `pot`, and, killing the process inside the jail, will automatically return without any zombie.
However, `tinirc` is not waiting for SIGCHILD, and that can generate zombies.
We need to extend our test base to catch more of this bugs.
What kind of application was causing this issue? A python one, maybe?

**Comment by grembo** [comment]
Simply nginx from nginx-full.job (like in the example workaround above). Probably any executable could cause the problem, reminds me of daemontools, where you would see similar issues if a run scripts doesn't exec its children probably. As the exec patch should fix the issue, I'm closing this.
