### ISSUE TITLE
Starting multiple jobs new pot imagein parallel won't work

### ISSUE THREAD

**Issue by grembo** [trivago/nomad-pot-driver#17]
When running a group of count > 1 for a specific image for the first time,
the driver runs "pot prepare" in parallel for each of them, leading to two
of them failing.

Example:

```
job "nginx" {
  datacenters = ["dc1"]
  type        = "service"

  group "group1" {
    count = 3
 ...
```
(modified basic nginx-full.job example, setting count to 3).

It's easy to reproduce:
1. Create job that uses a group that uses count > 1
2. Make sure the image hasn't been installed yet (check `pot list`)
3. run `nomad run myjob`
4. Perceive parallel invocations of `pot prepare...`
5. Perceive failed allocations

**Comment by pizzamig** [comment]
ah, without the image already present! good catch!
We already have a mechanism to protect commands that cannot be executed at the same time, but it's only protecting few commands. I'll have to extend this protection in `pot`

**Comment by grembo** [comment]
> ah, without the image already present! good catch!
> We already have a mechanism to protect commands that cannot be executed at the same time, but it's only protecting few commands. I'll have to extend this protection in `pot`

Those other commands seem to be locked in _common.sh_. A simple approach would be to add _prepare_ to the list of locked commands in the case statement, but probably something smarter would be better, so that other pot commands are not blocked while prepare is downloading a file (which might take some time). In the meantime I'll open a pull request for that naive approach, as it will at least prevent breakage.

**Comment by grembo** [comment]
This has been fixed/worked around in pot, so I'm closing it here.
