### ISSUE TITLE
Health checks not working with latest consul/nomad/pot

### ISSUE THREAD

**Issue by bretton** [trivago/nomad-pot-driver#28]
I'm having a problem with health checks when running pot images via nomad.

* pot version: 0.12.0
* Nomad v1.1.0
* nomad-pot-driver-0.7.0
* Consul v1.9.9

truncated job file:
```
job "myjob" (
  group "group1" (
    network {
      port "myport" {
         static = 26000
       }
    }
...
      service {
        port = "myport"
        ....
        check {
          type     = "tcp"
          port     = "myport"
          interval = "60s"
          timeout  = "30s"
        }
...
```
consul error for health checks
```
consul[37911]: 2021-09-23T20:33:26.079+0200 [WARN]  agent: Check socket connection failed: check=_nomad-check-32ee4f073dcbc65dcae6a08146107146c92a7a0d error="dial tcp X.X.X.X:26000: connect: connection refused" 
```

I've tried multiple variations specifying network types and nothing I'm doing exposes the port on the host for health checks.

Additionally, jobs won't run if config stanza has the following nomad-pot-driver documented options:

```
  network_mode = "public-bridge" 
  port_map = {
    myport = "26000"
  }
```

or 

```
  network_mode = "host" 
  port_map = {
    myport = "26000"
  }
```

it fails with the error
```
error="rpc error: code = Unknown desc = unable to create container: <nil>"
```

However this works on older FreeBSD12_2 instances. And it works if the port_map removed.

How do I get a port open on the host to the pot image, to perform health checks on things like smtp and http?

When I leave out the non-working stuff, image runs, but there doesn't seem to be bridging from configured host port to image service.

**Comment by hny-gd** [comment]
Note: The difference is about running pot images built with FreeBSD 13, i.e. it no longer works with FreeBSD 13 but under the conditions states above...

**Comment by bretton** [comment]
If I adjust the job file to move network settings under resources (nomad docs suggest as above), then it works fine on an older setup with FreeBSD12_2 and Nomad v0.11.3 and nomad-pot-driver-0.7.0, and opens ports to NAT through to job image.

```
job "myjob" (
  group "group1" (
    task "mytask" {
      service {
        port = "myport"
        ....
        check {
          type     = "tcp"
          port     = "myport"
          interval = "60s"
          timeout  = "30s"
        }
...
      resources {
        cpu = 1000
        memory = 1024
        network {
          port "myport" {
            static = 26000
            to = 25
          }
        }
       }
     }
...
```

**Comment by bretton** [comment]
When I include the network bit under resources in a job file for freebsd13 host, the image runs, even with port_map set, but no ports are opened on the host to the internal image. 

Consul on the host then fails to perform health checks because no port is open.

Summary:
- nomad documented way with network stanza under group doesn't work to open ports
- setting network stanza under resources works correctly on freebsd12_2 and freebsd13
BUT
- ports aren't opened on freebsd13

**Comment by bretton** [comment]
My apologies, this seems to be related to pot and not the pot-nomad-driver. 

As per https://github.com/pizzamig/pot/pull/167 the issue is with pot 0.12.0.

With pot 0.11.2 the ports are opened and ncat works. 

But it no longer works with pot 0.12.0. 

Will resolve via fixes for pot.
