### ISSUE TITLE
Does not support multiple tasks

### ISSUE THREAD

**Issue by perrymanuk** [trivago/nomad-pot-driver#3]
Currently with the naming convention of the pot driver there is a conflict in the naming of the jails when trying to create multiple tasks in one group since the task name isn't included and only the alloc id is used which isn't unique between tasks in a group.

TODO:
Prepend task name to jails created by pot

**Comment by ebarriosjr** [comment]
Working on it...

**Comment by ebarriosjr** [comment]
Issue fixed.
